### ISSUE TITLE
ICR Resource Group Needs to be passed in

### ISSUE THREAD

**Issue by daniel-butler-irl** [IBM/gen-ai-rag-watsonx-sample-application#8]
In the build setup script, we cannot just deploy into the default resource group, this needs to be set by the user. The current implementation has the side effect of not working on IBM Cloud accounts created pre-2019 where the default resource group was named `default`
https://github.com/IBM/gen-ai-rag-watsonx-sample-application/blob/main/scripts/build_setup.sh#L103

**Comment by ocofaigh** [comment]
Fixed in https://github.com/IBM/gen-ai-rag-watsonx-sample-application/pull/11
@daniel-butler-irl @brendankellyibm I have no access to close this issue
